### ISSUE TITLE
Replace fatal jam with container fell off

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#106]

**Comment by Enzoman34** [comment]
It was way more common

**Comment by terabyte128** [comment]
I changed the button, do you want to change the database entry too?

**Comment by terabyte128** [comment]
@Enzoman34 y/n?
probably yes?

**Comment by Enzoman34** [comment]
Actually, just delete every instance of Fatal jam

**Comment by terabyte128** [comment]
@Enzoman34 and get rid of the variable entirely?

**Comment by Enzoman34** [comment]
Yes.

**Comment by Enzoman34** [comment]
And add a column for container fell off

**Comment by terabyte128** [comment]
doneski
