### ISSUE TITLE
Some way for team managers to edit their teams data

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#107]
A lot of teams did shit data. We need some way for their managers to correct their mistakes without telling me to fix it or throwing away their data

**Comment by terabyte128** [comment]
Correct mistakes, or just delete the junk matches?

**Comment by Enzoman34** [comment]
Both

**Comment by terabyte128** [comment]
Finished, essentially. Needs better editing for tote stack locations.

**Comment by JayKingsFrc** [comment]
I don't know for the other pages, but for the edit data page, "back" button merely a bigger alternative of the browser-intact back button. Please wire the button linked to main page.

**Comment by JayKingsFrc** [comment]
Could you redesign the edit data page, so that I can just scroll down the data table, and also variable names stay on top while scrolling?

**Comment by terabyte128** [comment]
@JayKingsFrc draw me a diagram so I know what you mean and I'll consider it

**Comment by Enzoman34** [comment]
I think he wants to see an excel sheet with the data. Unfortunately this is almost impossible on mobile to look good.

**Comment by terabyte128** [comment]
Oh I see. Yeah, that won't really work well on mobile. I could give it a shot but I'm not sure how I'd be able to format it. Low priority at any rate.

**Comment by JayKingsFrc** [comment]
Yes low priority and kinda like excel.
I have seen some websites that work fine on mobile, but it's fine if it's hard to do.

**Comment by terabyte128** [comment]
closing this. @JayKingsFrc please create a new issue if you'd like to see a page for that (since it would likely be a separate page versus a reworking of this one)
