### ISSUE TITLE
Robot Selection Data Validation

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#113]
Instead of having a team select a robot and having alliance auto selected, make them select an alliance and make them choose from a set of three. We had a lot of problems with teams scouting robots that didn't exist or double scouting robots because similar number (like 2605 and 2606) on different alliances.

**Comment by Enzoman34** [comment]
Also change the order so it is:
Match:
Alliance:
Robot:

**Comment by JayKingsFrc** [comment]
Match schedule does not release until a couple hour before the match starts. Even then I do not know if they publish it right away on online. It seemed like USFirst had some issue with their system this year, too. I would love the idea, but is it timely viable?

**Comment by terabyte128** [comment]
I didn't do exactly this but something similar.
@JayKingsFrc is right though, it won't really apply much until it's too late.
