### ISSUE TITLE
Switch Warning Color and Message Color

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#114]
Make messages orange and bugs red. It just seems weird to have a red message and an orange bug. If there is a reason for this, never mind.

**Comment by terabyte128** [comment]
@Enzoman34 what messages? what bugs? where?

**Comment by Enzoman34** [comment]
Warning: (Should be red)
![image](https://cloud.githubusercontent.com/assets/1330515/6494446/b830703c-c276-11e4-9a6e-8639295639eb.png)
Message: (Shouldn't be Red)
![image](https://cloud.githubusercontent.com/assets/1330515/6494456/c2245bc6-c276-11e4-8728-d76f61ed6574.png)

**Comment by terabyte128** [comment]
switched
