### ISSUE TITLE
Change text on Tableau page

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#120]
- [x] On the line "You can use Tableau (included with your Kit of Parts) to help sort your data." change link from tableau.com to tableau.com/first-robotics (It still has a download link at the top). 

- [x] Change the text of "You can use Tableau (included with your Kit of Parts) to help sort your data." to "You can use Tableau to access and analyze your data. Access your 5 keys by having a mentor log onto TIMS ( link to https://my.usfirst.org/frc/tims/site.lasso) and checking the virtual Kit of Parts. "

**Comment by terabyte128** [comment]
Updated!
