### ISSUE TITLE
Test Match Scouting Button

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#122]
Make a separate button on match scouting labeled "Practice Scouting"

Have it go to identical match scouting except with some text explaining at the bottom that the data they collect will be saved to the test location and this page is for practicing scouting and training scouts only. Have a warning to make sure they aren't using this page to scout real matches on accident.

Then, have it be normal match scouting but it sets the location to Test.

Doing this will let new adopters practice without having to sign out and sign back in. We had a lot of problems with scouts forgetting to sign out of test location when they start scouting a real event.

**Comment by JayKingsFrc** [comment]
brilliant

**Comment by terabyte128** [comment]
added it
