### ISSUE TITLE
Partial completion matches submitted on accident

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#124]
How to reproduce:
scout a match, get past auto position, use back buttons to get back to main menu, start scouting a new match, submit that data, both matches will be submitted even if match 1 wasn't a complete record. 

At least I think that is what I think is happening.

Solution: Discard any incomplete matches before pushing (check for if match score is null)

**Comment by terabyte128** [comment]
Cannot reproduce. This may have been an issue from a while ago that I already fixed. There is already a check for unfinished matches before data is submitted.
