### ISSUE TITLE
Tote Stack Bug

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#125]
![image](https://cloud.githubusercontent.com/assets/1330515/6493510/fd97a818-c26f-11e4-89f5-42ab81e9347e.png)
![image](https://cloud.githubusercontent.com/assets/1330515/6493520/12952a7e-c270-11e4-8a95-4a710f6e390e.png)

also it still unselects the default number when you select a starting height
also new stack should be made the default starting height when you make a tote stack

**Comment by terabyte128** [comment]
It doesn't do that anymore. Maybe you have a cached version or something?
Fixed formatting issues.
I disagree that the "new stack" should be selected automatically, because it will make it too easy to accidentally click through.
