### ISSUE TITLE
Switches are weird

### ISSUE THREAD

**Issue by Akorn10ds** [FIRST-4030/frc-scout-2015#127]
What ever this is?
![image](https://cloud.githubusercontent.com/assets/10788753/6497937/04aadf32-c29b-11e4-814c-1c6e36aaf0e0.png)

**Comment by terabyte128** [comment]
@Akorn10ds what device?

**Comment by Akorn10ds** [comment]
My school computer. 
Hp Elitebook 2570p, Window 7, Chrome browser. etc.

**Comment by terabyte128** [comment]
@Akorn10ds  Huh. That's weird. Chrome should work fine. Can you right click -> inspect element, hit the "console" tab, reload the page and see if any errors appear?

**Comment by Akorn10ds** [comment]
Yeah, that seems to fix it, but once I reload Match Scouting it returns to being buggy. Is this something just in my configuration?

**Comment by terabyte128** [comment]
It seems like it, I've tested chrome, firefox and safari and have not encountered any issues. Does the same thing happen in scout management page?

**Comment by terabyte128** [comment]
@Akorn10ds OK if i close this? has it resolved itself?

**Comment by Akorn10ds** [comment]
:0 yeah sure, since this seems like it's just on my computer

**Comment by Akorn10ds** [comment]
It doesn't happen in the scout management page, but it does in Pit scouting? Eh, whatever

**Comment by Enzoman34** [comment]
It showed up for me recently briefly and then stopped. It was on the scout management page. Once I scrolled down and the page fully loaded it went away.
