### ISSUE TITLE
Undo dead-bot

### ISSUE THREAD

**Issue by Akorn10ds** [FIRST-4030/frc-scout-2015#138]
A way to undo selecting Deadbot. Robots pause for a while and then start moving again so scouts prematurely select dead bot. 
(Maybe make it a switch somehow, or move it to end match?)

**Comment by Enzoman34** [comment]
Perhaps if they hit it, freeze all of the buttons except for an undo dead bot button so they don't forget to un-deadbotify the bot

**Comment by terabyte128** [comment]
dead bot i took to mean "died at some point, even if it came back to life." diferent?

**Comment by Enzoman34** [comment]
I agree with you. Let's close this

**Comment by terabyte128** [comment]
great
