### ISSUE TITLE
Tele Stacks

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#14]
"Height before Addition" rename to "Totes stacked on top of" and change the label of 0 to "New Stack" (but still store it as 0).

"Height after addition" should be named to "Totes Added to Stack." This of course changes the definition of field but it is still similar and useful.

**Comment by terabyte128** [comment]
changed title

**Comment by terabyte128** [comment]
Changed height after addition to totes added and updated database column name appropriately.
