### ISSUE TITLE
autonomous container logic error

### ISSUE THREAD

**Issue by JayKingsFrc** [FIRST-4030/frc-scout-2015#141]
there are robots which scores containers and still maintain the possession of them for telep. For now users need to recollect the container if the robot scores container by collecting them and keeping the possession

**Comment by Enzoman34** [comment]
rephrased: if a robot geta container in auto they shouldnt have to collect it again in tele to score it

**Comment by broomweed** [comment]
Related: #137.

**Comment by terabyte128** [comment]
removed limitation of being unable to stack containers in tele.
