### ISSUE TITLE
Tele Stacks Data Validation

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#15]
If we want to assume that they aren't going to stack it to over 6, could you change the colors of "Totes added to Stack" to make sure they don't go over the 6 limit?

Like if they select 3 for "Totes already in stack", make 4,5, and 6 a much lighter color to re-emphasize that those options are invalid. We can decide later if we just want to straight-up deny them from selecting that option.

Also, we should restrict the stack locations to the actual scoring platforms. Again, we can find a different image for that.

**Comment by terabyte128** [comment]
Made stacks over 6 disabled.

**Comment by terabyte128** [comment]
Obvious that they cannot go over 6
