### ISSUE TITLE
Website Manager Match Edit Erorr

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#153]
![image](https://cloud.githubusercontent.com/assets/1330515/6606125/8be472fe-c7f2-11e4-83ad-83f8cba08e30.png)

Also consider loading only the first 100 records before they click a button to load all of them. On mobile it is overwhelming and takes forever to load.

**Comment by Enzoman34** [comment]
Can we close it? It seems fixed now.

**Comment by terabyte128** [comment]
um i didn't fix it

**Comment by terabyte128** [comment]
![screen shot 2015-03-11 at 7 07 17 pm](https://cloud.githubusercontent.com/assets/1189703/6610802/ddc900ec-c821-11e4-9f7e-170b8d72a81d.png) fixed

**Comment by terabyte128** [comment]
results > 100 are truncated
