### ISSUE TITLE
auto select no auto if robot has no auto actions

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#154]
pretty self explanitory

**Comment by terabyte128** [comment]
but the robot might move or something, just do it incorrectly. no auto != no points

see #139

**Comment by terabyte128** [comment]
again, see #139

**Comment by Enzoman34** [comment]
Ok. How about we change the name from no-auto to no auto scouted actions. And it is done if they dont click any buttons for auto at all.

**Comment by terabyte128** [comment]
can't we just leave the button to be more obvious and leave it like that

**Comment by Enzoman34** [comment]
actually, fuck it. I can calculate no auto in Tableau

**Comment by terabyte128** [comment]
Good
