### ISSUE TITLE
Pending Matche entry error

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#155]
I keep on getting this error were it wont let me submit my pending match (Probably because it isn't complete) on phone when I have connection to the internet. Also wont let me delete my pending match.

**Comment by terabyte128** [comment]
it's because you have too large of a final match score.

**Comment by terabyte128** [comment]
or somehow your match number is null, which should never happen. try clearing localStorage.

**Comment by Enzoman34** [comment]
It's on a phone. Can you have the website delete matches that are breaking the rules?

**Comment by terabyte128** [comment]
try again...

**Comment by Enzoman34** [comment]
Fixed. Close

**Comment by terabyte128** [comment]
great
