### ISSUE TITLE
team profile with no matches scouted

### ISSUE THREAD

**Issue by terabyte128** [FIRST-4030/frc-scout-2015#157]
![screen shot 2015-03-13 at 9 32 15 am](https://cloud.githubusercontent.com/assets/1189703/6642712/0431beac-c964-11e4-837a-d9a8d71a0322.png)

**Comment by terabyte128** [comment]
![screen shot 2015-03-13 at 9 32 15 am](https://cloud.githubusercontent.com/assets/1189703/6642709/fd586180-c963-11e4-8647-85c0405edf1d.png)

**Comment by broomweed** [comment]
Whoa wait it closed it automatically when I said "fix #157" -- that's so cool
