### ISSUE TITLE
collecting litter javelin data option

### ISSUE THREAD

**Issue by JayKingsFrc** [FIRST-4030/frc-scout-2015#161]
Teams like Sea monster guarantees 30-40 points per match which is about 1/3 of the highest qual. average score for the regional. Without it, we have a big hole in our data

**Comment by Enzoman34** [comment]
Iti s VERY hard for scouts to watch bot ha robot and a human player at once.

**Comment by JayKingsFrc** [comment]
I very much agree. It's impossible. That's why we have 1-2 scouts for Noodle javelin. I realized you were using point ranking graphs, and thought it may interest you.

**Comment by Enzoman34** [comment]
Maybe a different type of scouting menu? Like a simplified one that scouts
the entire alliance at once but only for noodling

**Comment by JayKingsFrc** [comment]
I'd love to see that idea

**Comment by JayKingsFrc** [comment]
I see your point of not being bothered by noodlers at all, but it's pretty neat specialty to see from some 2nd-pick teams

**Comment by terabyte128** [comment]
Leave a comment
