### ISSUE TITLE
Discard Data

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#22]
I am going to assume that there are going to be like 3 confirmation pop ups to confirm why the data should be deleted. Preferably put in a text box so they can say why the data was deleted.

**Comment by terabyte128** [comment]
yes, once i implement actual data pushing there will be multiple warnings

**Comment by terabyte128** [comment]
Very obvious, difficult to ignore warnings, including having to enter the scouted team's number, before the data is deleted.
