### ISSUE TITLE
Tele Totes Aquire

### ISSUE THREAD

**Issue by Akorn10ds** [FIRST-4030/frc-scout-2015#34]
On Tablets you need to scroll. I don't know why.

**Comment by terabyte128** [comment]
@Akorn10ds do you mean scroll to see all the buttons? or just that there is a little play at the top and bottom?

**Comment by terabyte128** [comment]
I'm able to reproduce the latter on a n7 but not the former

**Comment by terabyte128** [comment]
Should be fixed
