### ISSUE TITLE
Changing Password Bug

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#37]
Returning to the home page after changing the password brings up this 404 page
Page not found (404)
Request Method:	GET
Request URL:	http://5wl7lvkg.apps.lair.io/accounts/login/?next=/account/password/
Using the URLconf defined in frc_scout_2015.urls, Django tried these URL patterns, in this order:
^admin/
^ ^$ [name='index']
^ ^login/$ [name='login']
^ ^logout/$ [name='logout']
^ ^create/$ [name='create_account']
^ ^json/team_exists/$ [name='check_if_team_exists']
^ ^json/username_exists/$ [name='check_if_username_exists']
^ ^json/locations/$ [name='get_locations']
^ ^manage/scouts/$ [name='view_scouts']
^ ^manage/scouts/update/$ [name='update_scouts']
^ ^account/profile/$ [name='update_profile']
^ ^account/password/$ [name='update_password']
^ ^scouting/match/$ [name='match_scouting']
^ ^scouting/match/submit/$ [name='submit_match_scouting_data']
The current URL, accounts/login/, didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

**Comment by terabyte128** [comment]
Fixed URL
