### ISSUE TITLE
Actually a problem: Doesn't fit on Nexus 7 screen

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#38]
I can give you some screen shots, but it doesn't scale verticaly onto a single screen. That is a big problem. We wanted to avoid scrolling at all cost.

**Comment by terabyte128** [comment]
Working to fix this. It fits on my test screen but not on a real Nexus. Further testing will be performed with my N7 -- most pages fit now.

**Comment by terabyte128** [comment]
All pages now should fit (verify with your newer nexuses)
