### ISSUE TITLE
Full Screen App Problems (Phone)

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#41]
For my phone (Doesn't seem to be a problem on the tablet), whenever there is a confirmation (like confirming auto starting location), it exits the page and opens up a new instance of chrome. I have no idea why and it happens every time.

**Comment by terabyte128** [comment]
Cannot reproduce on my phone with running as webapp.

**Comment by terabyte128** [comment]
closing bc cannot reproduce...
