### ISSUE TITLE
Renaming Labels (Again)

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#42]
Ok, sorry about this again. We have been testing this with some people and this will help

Every instance of the word "Bin" change to Container"
"Moved Yellow" to "Yellow Tote in Zone"
"Acquired Step" to "Acquired from Step"
"Acquired Ground" to "Acquired from Ground"
"Moved Bin" to "Moved Container to Zone"
"Ended in Auto Zone" to "Robot ended in Auto Zone" 
It is in the bins column so it is confusing. If you could find a way to get it out of that column that would be awesome.

**Comment by terabyte128** [comment]
fixed containers and names
