### ISSUE TITLE
Invalid Login Error

### ISSUE THREAD

**Issue by theoster** [FIRST-4030/frc-scout-2015#44]
Tried to log in as enzoman with a lower case e.  Password was 123456, should the thing be case sensitive.

DoesNotExist at /login/
User matching query does not exist.
Request Method:	POST
Request URL:	http://5wl7lvkg.apps.lair.io/login/
Django Version:	1.7.3
Exception Type:	DoesNotExist
Exception Value:	
User matching query does not exist.
Exception Location:	/mnt/data/.local/lib/python2.7/site-packages/django/db/models/query.py in get, line 357
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/mnt/project',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/mnt/data/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Fri, 6 Feb 2015 02:24:31 +0000
Traceback Switch to copy-and-paste view

/mnt/data/.local/lib/python2.7/site-packages/django/core/handlers/base.py in get_response
                    response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/mnt/project/frc_scout/views/session_views.py in login_view
                email = User.objects.get(email=username) ...
▶ Local vars
/mnt/data/.local/lib/python2.7/site-packages/django/db/models/manager.py in manager_method
                return getattr(self.get_queryset(), name)(*args, **kwargs) ...
▶ Local vars
/mnt/data/.local/lib/python2.7/site-packages/django/db/models/query.py in get
                self.model._meta.object_name) ...
▶ Local vars
Request information

GET
No GET data
POST
Variable	Value
username	
u'enzoman34@gmail.com'
csrfmiddlewaretoken	
u'I3xoLS89qXraQCZ7R7xu5hA0OWt2OGG3'
password	
u'123456'
location	
u'MAR District - Upper Darby Event'
FILES
No FILES data
COOKIES
Variable	Value
csrftoken	
'I3xoLS89qXraQCZ7R7xu5hA0OWt2OGG3'
META
Variable	Value
wsgi.multiprocess	
False
RUN_MAIN	
'true'
HTTP_REFERER	
'http://5wl7lvkg.apps.lair.io/login/'
SERVER_PROTOCOL	
'HTTP/1.0'
SERVER_SOFTWARE	
'WSGIServer/0.1 Python/2.7.6'
SCRIPT_NAME	
u''
SL_ENV	
'1'
PATH_INFO	
u'/login/'
HTTP_ORIGIN	
'http://5wl7lvkg.apps.lair.io'
HOME	
'/mnt/user'
QUERY_STRING	
''
PATH	
'/mnt/data/.local/bin:/mnt/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/data/.gem/bin:/mnt/data/.node/bin'
PYTHONUNBUFFERED	
'1'
wsgi.errors	
<open file '<stderr>', mode 'w' at 0x7fd13cfd61e0>
HTTP_X_REAL_IP	
'216.186.51.175'
LANG	
'en_US.UTF-8'
TERM	
'xterm'
HTTP_USER_AGENT	
'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36'
TZ	
'UTC'
HTTP_COOKIE	
'csrftoken=I3xoLS89qXraQCZ7R7xu5hA0OWt2OGG3'
LANGUAGE	
'en_US:en'
REMOTE_ADDR	
'192.241.232.145'
SHLVL	
'1'
wsgi.url_scheme	
'http'
SERVER_PORT	
'8000'
PYTHONUSERBASE	
'/mnt/data/.local/'
CONTENT_LENGTH	
'141'
HTTP_X_FORWARDED_PROTO	
'http'
wsgi.multithread	
True
wsgi.input	
<socket._fileobject object at 0x7fd138120250>
HTTP_CONNECTION	
'close'
HTTP_HOST	
'5wl7lvkg.apps.lair.io'
PIP_USER	
'1'
LC_ALL	
'en_US.UTF-8'
HTTP_CACHE_CONTROL	
'max-age=0'
_	
'./manage.py'
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
wsgi.version	
(1, 0)
SERVER_NAME	
'c0b80636ed82'
GATEWAY_INTERFACE	
'CGI/1.1'
HTTP_X_FORWARDED_FOR	
'216.186.51.175'
CSRF_COOKIE	
u'I3xoLS89qXraQCZ7R7xu5hA0OWt2OGG3'
OLDPWD	
'/mnt/project'
HOSTNAME	
'c0b80636ed82'
HTTP_ACCEPT_LANGUAGE	
'en-US,en;q=0.8'
HTTP_ACCEPT_ENCODING	
'gzip, deflate'
DJANGO_NOCOLOR	
'1'
wsgi.run_once	
False
PWD	
'/var/www/app'
REQUEST_METHOD	
'POST'
DJANGO_SETTINGS_MODULE	
'frc_scout_2015.settings'
CONTENT_TYPE	
'application/x-www-form-urlencoded'
wsgi.file_wrapper	
''
REMOTE_HOST	
''
SL_DJANGO_ROOT	
'.'
NPM_CONFIG_PREFIX	
'/mnt/data/.node'
Settings
Using settings module frc_scout_2015.settings
Setting	Value
COMPRESS_URL	
'/static/'
COMPRESS_OUTPUT_DIR	
u'CACHE'
COMPRESS_TEMPLATE_FILTER_CONTEXT	
{u'STATIC_URL': '/static/'}
USE_L10N	
True
COMPRESS_DATA_URI_MAX_SIZE	
1024
CSRF_COOKIE_SECURE	
False
LANGUAGE_CODE	
'en-us'
ROOT_URLCONF	
'frc_scout_2015.urls'
MANAGERS	
()
COMPRESS_CSS_HASHING_METHOD	
u'mtime'
BASE_DIR	
'/mnt/project'
TEST_NON_SERIALIZED_APPS	
[]
DEFAULT_CHARSET	
'utf-8'
IGNORABLE_404_URLS	
()
SESSION_SERIALIZER	
'django.contrib.sessions.serializers.JSONSerializer'
STATIC_ROOT	
'/mnt/project/frc_scout_2015/static'
COMPRESS_CLOSURE_COMPILER_ARGUMENTS	
u''
USE_THOUSAND_SEPARATOR	
False
COMPRESS_OFFLINE_MANIFEST	
u'manifest.json'
ALLOWED_HOSTS	
[]
MESSAGE_STORAGE	
'django.contrib.messages.storage.fallback.FallbackStorage'
EMAIL_SUBJECT_PREFIX	
'[Django] '
SEND_BROKEN_LINK_EMAILS	
False
STATICFILES_FINDERS	
('django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder',
 'compressor.finders.CompressorFinder')
SESSION_CACHE_ALIAS	
'default'
COMPRESS_CSSTIDY_ARGUMENTS	
u'--template=highest'
SESSION_COOKIE_DOMAIN	
None
SESSION_COOKIE_NAME	
'sessionid'
COMPRESS_YUGLIFY_JS_ARGUMENTS	
u'--terminal'
ADMIN_FOR	
()
TIME_INPUT_FORMATS	
('%H:%M:%S', '%H:%M:%S.%f', '%H:%M')
DATABASES	
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.sqlite3',
             'HOST': '',
             'NAME': 'dev.db',
             'OPTIONS': {},
             'PASSWORD': u'********************',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': 'UTC',
             'USER': ''}}
FILE_UPLOAD_DIRECTORY_PERMISSIONS	
None
SITE_URL	
'localhost'
COMPRESS_YUI_BINARY	
u'java -jar yuicompressor.jar'
FILE_UPLOAD_PERMISSIONS	
None
FILE_UPLOAD_HANDLERS	
('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
DEFAULT_CONTENT_TYPE	
'text/html'
COMPRESS_CSS_COMPRESSOR	
u'compressor.css.CssCompressor'
APPEND_SLASH	
True
FIRST_DAY_OF_WEEK	
0
DATABASE_ROUTERS	
[]
DEFAULT_TABLESPACE	
''
YEAR_MONTH_FORMAT	
'F Y'
COMPRESS_OFFLINE_TIMEOUT	
31536000
STATICFILES_STORAGE	
'django.contrib.staticfiles.storage.StaticFilesStorage'
CACHES	
{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
SERVER_EMAIL	
'root@localhost'
SESSION_COOKIE_PATH	
'/'
COMPRESS_PARSER	
u'compressor.parser.AutoSelectParser'
COMPRESS_OFFLINE_CONTEXT	
{u'STATIC_URL': '/static/'}
MESSAGE_TAGS	
{40: 'danger'}
COMPRESS_CACHE_BACKEND	
u'default'
SILENCED_SYSTEM_CHECKS	
[]
MIDDLEWARE_CLASSES	
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'frc_scout.middleware.ContentLengthMiddleware')
USE_I18N	
True
THOUSAND_SEPARATOR	
','
SECRET_KEY	
u'********************'
LANGUAGE_COOKIE_NAME	
'django_language'
DEFAULT_INDEX_TABLESPACE	
''
TRANSACTIONS_MANAGED	
False
LOGGING_CONFIG	
'logging.config.dictConfig'
SIGNING_BACKEND	
'django.core.signing.TimestampSigner'
TEMPLATE_LOADERS	
('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader')
WSGI_APPLICATION	
'frc_scout_2015.wsgi.application'
TEMPLATE_DEBUG	
False
X_FRAME_OPTIONS	
'SAMEORIGIN'
CSRF_COOKIE_NAME	
'csrftoken'
FORCE_SCRIPT_NAME	
None
USE_X_FORWARDED_HOST	
False
COMPRESS_CSSTIDY_BINARY	
u'csstidy'
SESSION_COOKIE_SECURE	
False
PROJECT_DIRNAME	
'frc_scout_2015'
COMPRESS_DEBUG_TOGGLE	
None
COMPRESS_VERBOSE	
False
CSRF_COOKIE_DOMAIN	
None
FILE_CHARSET	
'utf-8'
DEBUG	
True
LANGUAGE_COOKIE_DOMAIN	
None
COMPRESS_JS_FILTERS	
[u'compressor.filters.jsmin.JSMinFilter']
DEFAULT_FILE_STORAGE	
'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS	
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'frc_scout',
 'compressor')
LANGUAGES_BIDI	
('he', 'ar', 'fa', 'ur')
COMMENTS_ALLOW_PROFANITIES	
False
COMPRESS_YUI_CSS_ARGUMENTS	
u''
STATICFILES_DIRS	
()
PREPEND_WWW	
False
SECURE_PROXY_SSL_HEADER	
None
LANGUAGE_COOKIE_AGE	
None
SESSION_COOKIE_HTTPONLY	
True
DEBUG_PROPAGATE_EXCEPTIONS	
False
INTERNAL_IPS	
()
MONTH_DAY_FORMAT	
'F j'
LOGIN_URL	
'/login/'
SESSION_EXPIRE_AT_BROWSER_CLOSE	
False
TIME_FORMAT	
'P'
COMPRESS_STORAGE	
u'compressor.storage.CompressorFileStorage'
AUTH_USER_MODEL	
'auth.User'
DATE_INPUT_FORMATS	
('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')
COMPRESS_CSS_FILTERS	
[u'compressor.filters.css_default.CssAbsoluteFilter']
AUTHENTICATION_BACKENDS	
('django.contrib.auth.backends.ModelBackend',)
EMAIL_HOST_PASSWORD	
u'********************'
COMPRESS_REBUILD_TIMEOUT	
2592000
PASSWORD_RESET_TIMEOUT_DAYS	
u'********************'
SESSION_FILE_PATH	
None
CACHE_MIDDLEWARE_ALIAS	
'default'
SESSION_SAVE_EVERY_REQUEST	
False
NUMBER_GROUPING	
0
SESSION_ENGINE	
'django.contrib.sessions.backends.db'
COMPRESS_YUGLIFY_BINARY	
u'yuglify'
CSRF_FAILURE_VIEW	
'django.views.csrf.csrf_failure'
CSRF_COOKIE_PATH	
'/'
COMPRESS_CACHE_KEY_FUNCTION	
u'********************'
LOGIN_REDIRECT_URL	
'/accounts/profile/'
PROJECT_ROOT	
'/mnt/project/frc_scout_2015'
DECIMAL_SEPARATOR	
'.'
COMPRESS_PRECOMPILERS	
()
COMPRESS_MTIME_DELAY	
10
LOCALE_PATHS	
()
TEMPLATE_STRING_IF_INVALID	
''
LOGOUT_URL	
'/accounts/logout/'
EMAIL_USE_TLS	
False
TEMPLATE_DIRS	
('/mnt/project/frc_scout_2015/templates',)
FIXTURE_DIRS	
()
EMAIL_HOST	
'localhost'
DATE_FORMAT	
'N j, Y'
MEDIA_ROOT	
'/mnt/project/frc_scout_2015/static/media'
DEFAULT_EXCEPTION_REPORTER_FILTER	
'django.views.debug.SafeExceptionReporterFilter'
ADMINS	
()
FORMAT_MODULE_PATH	
None
DEFAULT_FROM_EMAIL	
'webmaster@localhost'
COMPRESS_ROOT	
'/mnt/project/frc_scout_2015/static'
MEDIA_URL	
'/static/media/'
DATETIME_FORMAT	
'N j, Y, P'
COMPRESS_YUI_JS_ARGUMENTS	
u''
COMPRESS_JS_COMPRESSOR	
u'compressor.js.JsCompressor'
DISALLOWED_USER_AGENTS	
()
ALLOWED_INCLUDE_ROOTS	
()
COMPRESS_MINT_DELAY	
30
LOGGING	
{}
SHORT_DATE_FORMAT	
'm/d/Y'
TEST_RUNNER	
'django.test.runner.DiscoverRunner'
COMPRESS_ENABLED	
False
CACHE_MIDDLEWARE_KEY_PREFIX	
u'********************'
COMPRESS_OFFLINE	
False
TIME_ZONE	
'UTC'
FILE_UPLOAD_MAX_MEMORY_SIZE	
2621440
COMPRESS_YUGLIFY_CSS_ARGUMENTS	
u'--terminal'
EMAIL_BACKEND	
'django.core.mail.backends.smtp.EmailBackend'
COMPRESS_JINJA2_GET_ENVIRONMENT	
<function JINJA2_GET_ENVIRONMENT at 0x7fd139fe7668>
EMAIL_USE_SSL	
False
TEMPLATE_CONTEXT_PROCESSORS	
('django.contrib.auth.context_processors.auth',
 'django.core.context_processors.debug',
 'django.core.context_processors.i18n',
 'django.core.context_processors.media',
 'django.core.context_processors.static',
 'django.core.context_processors.tz',
 'django.contrib.messages.context_processors.messages',
 'django.core.context_processors.request')
MIGRATION_MODULES	
{}
SESSION_COOKIE_AGE	
1209600
SETTINGS_MODULE	
'frc_scout_2015.settings'
NEVERCACHE_KEY	
u'********************'
USE_ETAGS	
False
LANGUAGES	
(('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmal'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-cn', 'Simplified Chinese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese'),
 ('zh-tw', 'Traditional Chinese'))
COMPRESS_CLOSURE_COMPILER_BINARY	
u'java -jar compiler.jar'
FILE_UPLOAD_TEMP_DIR	
None
CSRF_COOKIE_AGE	
31449600
STATIC_URL	
'/static/'
EMAIL_PORT	
25
USE_TZ	
True
SHORT_DATETIME_FORMAT	
'm/d/Y P'
PASSWORD_HASHERS	
u'********************'
ABSOLUTE_URL_OVERRIDES	
{}
LANGUAGE_COOKIE_PATH	
'/'
CACHE_MIDDLEWARE_SECONDS	
600
CSRF_COOKIE_HTTPONLY	
False
DATETIME_INPUT_FORMATS	
('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')
EMAIL_HOST_USER	
''
PROFANITIES_LIST	
u'********************'
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page.

**Comment by terabyte128** [comment]
Fixed
