### ISSUE TITLE
Auto-Scroll to Resume in previous screen

### ISSUE THREAD

**Issue by Akorn10ds** [FIRST-4030/frc-scout-2015#46]
when finishing an action in teleoperated mode, return to the previous screen and return to where the user was last scrolled to.

**Comment by terabyte128** [comment]
@Akorn10ds you mean when you go back to the main teleop screen? ideally there should be no scrolling at all on that page.

**Comment by Akorn10ds** [comment]
I think if you use a smaller device like a phone on it's side, it'll scroll. Yeah, I don't remember the context of this too well

**Comment by terabyte128** [comment]
this is pretty much impossible to reasonably implement
