### ISSUE TITLE
Autonomous

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#6]
Moved to auto zone should be a check box.
Yellow totes stacked or moved shouldn't be more than 3
Acquired step shouldn't be more than 4
Acquired ground shouldn't be more than 3
Also, it might be good to make "fouls and other" red.

**Comment by terabyte128** [comment]
changed button colors

**Comment by terabyte128** [comment]
added max values (with a cool method)

### still remaining
* Moved to auto zone should be a check box.

@Enzoman34 right now there is no option for moved to auto zone, should I add it?

**Comment by Enzoman34** [comment]
Auto Moved is moved to auto zone. Currently Auto moved is a number field for some reason. It should be a check box.

**Comment by terabyte128** [comment]
Oh right. For some reason I thought that was totes moved. I'll fix it.

**Comment by terabyte128** [comment]
fixed

**Comment by terabyte128** [comment]
See commit 43492a62d48e89a44dd0af6e8e37b98aaf36b0f2
