### ISSUE TITLE
Slightly different green background for each row in a coloumn

### ISSUE THREAD

**Issue by emorye** [FIRST-4030/frc-scout-2015#62]
The point of coloring is so we don't need to look down very much. Remember, 1/4 a second makes a huge difference. Making the top green button slightly lighter and the bottom button slightly darker will make that 1/4 second difference.

**Comment by terabyte128** [comment]
@Enzoman34 thoughts?

**Comment by broomweed** [comment]
I'm going to call subitization on this one -- people can probably find the right thing in a set of 3 without many visual cues (it's either the top one, the middle one, or the bottom one); if there were like 5 or 6 this might be more necessary

**Comment by terabyte128** [comment]
i'm going with miles on this one, tried it and it looked weird
