### ISSUE TITLE
Coop Stack Switch

### ISSUE THREAD

**Issue by Akorn10ds** [FIRST-4030/frc-scout-2015#68]
Coopertition stack switch is weird?? It's twice as big and it slides from a weird blank to both ON/OFF

**Comment by Akorn10ds** [comment]
Oh wait, it's only if you reload the page on the Stacked screen, it's fine the first time. This might be avoidable normally?

**Comment by terabyte128** [comment]
````
yum fixed 
(             )
(   fixed     )
(     moo     )
 ------------- 
       O 
        O   ^__^
         o  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
````
