### ISSUE TITLE
Design Enhancments

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#7]
Ok. So I don't know how hard it is to do this, but it is something that helped our scouts a lot last year. Last year, no matter what screen you were in, the robot number you were scouting appeared somewhere on the page. It helped our scouts not get lost during boring matches.

On this app, could you put whatever robot they are scouting after the header? So like 
"Autonomous (3663)." Also to show what alliance they are on, could you replace the currently green buttons with a slight blue or red color based on whatever alliance they selected? Both of these things would improve the usability of the app.

**Comment by terabyte128** [comment]
Yes, we actually did this last year and I was planning on adding it this year. Just gotta figure out the nicest way to do so. 

We also had borders on the top/bottom to remind scouts of the alliance color (which is the only reason I was collecting alliance color data on the prematch screen).

**Comment by terabyte128** [comment]
added team number on title

**Comment by terabyte128** [comment]
added background color

**Comment by terabyte128** [comment]
Background color and team number finished.
