### ISSUE TITLE
-(minus) button bug

### ISSUE THREAD

**Issue by JayKingsFrc** [FIRST-4030/frc-scout-2015#71]
In"Scouting: Teleoperated" page, you cannot cancel totes "picked up" by clicking minus bottom once you submit them as a totes "stacked." More specifically, it only allows you to only subtract one tote from the "picked up."

Although this cancellation of totes "picked up" will not be common once a user submit them as a totes "stacked," but will probably happen occasionally.

**Comment by Enzoman34** [comment]
Right now you can only undo one action. We are trying to fix this but it involves a lot of structure changes and it is a lower priority than other base functionality bugs.

**Comment by JayKingsFrc** [comment]
Thanks for the reply and no worries I will just post all the bugs I see for your information but don't need to reply every time.

-Jay

**Comment by terabyte128** [comment]
Thank you for your report -- see #9
