### ISSUE TITLE
It isn't necessary to pick a team color at the beginning of the match

### ISSUE THREAD

**Issue by Skunk-Awol** [FIRST-4030/frc-scout-2015#76]
Steps to reproduce:
1. Go to pre-match
2. Don't pick a color
3. Click "autonomous"

**Comment by Enzoman34** [comment]
Sam, this might have something to do with the new TBA integration.

**Comment by terabyte128** [comment]
This is a feature not a bug.

**Comment by Skunk-Awol** [comment]
Colorless robots I like it /s

**Comment by terabyte128** [comment]
sssshhh

**Comment by terabyte128** [comment]
Fixed
