### ISSUE TITLE
Robot can start autonomous outside the field

### ISSUE THREAD

**Issue by Skunk-Awol** [FIRST-4030/frc-scout-2015#77]
Steps to reproduce:
1. Go to autonomous starting location
2. [click on the slightly-lighter blue area in the lower-left corner](http://puu.sh/g1jRi/d9e0eac1f7.png)
3. Confirm location

**Comment by Skunk-Awol** [comment]
probably other places too lol

**Comment by terabyte128** [comment]
This is kinda complicated to make work better and I don't think it's that important as long as your scouts aren't complete idiots.
