### ISSUE TITLE
Ghostly containers in autonomous

### ISSUE THREAD

**Issue by Skunk-Awol** [FIRST-4030/frc-scout-2015#78]
Steps to reproduce:
1. Go to autonomous
2. Acquire 4 containers from the step and 3 from the ground
3. Move 7 containers to the zone
4. Remove all containers from the step and the ground
5. (WTF NUMBER 1?) Attempt to add another container to the zone
6. (WTF NUMBER 2???) Remove 3 containers from the zone (notice the number of containers left)

**Comment by terabyte128** [comment]
Fixed! Also made the "Moved to zone" total auto-update when the first 2 are undone.
