### ISSUE TITLE
PreMatch AutoComplete

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#8]
The Blue alliance has an api for match schedule. If you change the order they enter the prematch to "Match", "alliance", "Robot." If the blue alliance has data for the event, the robot field could turn into a drop down to make sure they dont accidentally typo or enter in a different but similar robot. It makes it easier to scout for bots when you can only see the first 2 digits or something if they are blocked by other bots.

**Comment by terabyte128** [comment]
Saving this for later, after all other things work

**Comment by Enzoman34** [comment]
I would like to say this is really important. As far as long term issues goals go, this is the most important.

**Comment by terabyte128** [comment]
Added this functionality! 

It will not work until The Blue Alliance adds match schedules for each event (until then it will behave as it used to).
