### ISSUE TITLE
Randomly mashing buttons results in tens of thousands of totes in possession

### ISSUE THREAD

**Issue by Skunk-Awol** [FIRST-4030/frc-scout-2015#80]
Steps to reproduce:
1. Go to teleoperated
2. Pick up 30 totes
3. Create 3 stacks with random properties
4. Subtract 3 stacks
5. [um](http://puu.sh/g1jfZ/dd6732f5d0.png)

**Comment by Enzoman34** [comment]
This is actually amazing.

**Comment by terabyte128** [comment]
Lol, forgot a `parseInt()`, should be fixed now.
