### ISSUE TITLE
Pictures for Pit Scouting

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#87]
Can we add a way to upload a picture for the pit scouting

**Comment by Enzoman34** [comment]
could also be used for robot selection in prematch. Probably would put a button next to it that says show the picture so they dont have to use the data unless they need it.

**Comment by terabyte128** [comment]
We decided not to bother with pictures this year because nobody uses them last year. How important are they to you?

**Comment by JayKingsFrc** [comment]
My team scouts use bot photos as the primary means to identify the teams, esp. at the championship

**Comment by terabyte128** [comment]
OK, we will work on it.

**Comment by terabyte128** [comment]
Finished
