### ISSUE TITLE
App is fairly large for something designed to be loaded over 3G.

### ISSUE THREAD

**Issue by Skunk-Awol** [FIRST-4030/frc-scout-2015#89]
Some points a few of us came up with after some careful research:

 - [x] ~~Nothing is minified?~~
 - [ ] Unnecessary CSS (Do you need hover events on touchscreens?)
 - [ ] Do you need all of jQuery?
 - [x] Unnecessary markup (20 apple-touch-icon tags?)
 - [x] I'm not sure [this 75kb bootstrap plugin](http://frcscout.com/static/frc_scout/js/bootstrap-editable.min.js) is really necessary?
 - [x] ~~COMPRESS_ENABLED turned off?  (Because this is still debug?)~~
 - [ ] JQUERY??????????????????????????????????????

**Comment by emorye** [comment]
I agree. Although it wil be pulled down instantly on T-Mobile's Super Fast 4G LTE Network, data usage is a concern. Maybe using local storage as a cache could help that?

**Comment by dlom** [comment]
Likewise, it's obvious that you to use an asynchronous io.js NoSQL solution, utilizing the latest MVVM AngularJS technologies in order to create a seamless one-page-application that communicates with socket.io and and a JSON REST API in order to maximize the efficiency of T-Mobile's Super Fast 4G LTE Network.

Like, duh.

**Comment by terabyte128** [comment]
Compression will be turned on soon and that will minify things.

**Comment by terabyte128** [comment]
Also, do you want anything with match scouting to work? Why don't you go try to rewrite the entire 1200 line match scouting JavaScript page without jquery and see how it works. (document.getElementById, anyone?)

**Comment by dlom** [comment]
[what I did](https://remysharp.com/2013/04/19/i-know-jquery-now-what#jquery-free)

**Comment by terabyte128** [comment]
Minified & compressed a bunch of stuff, which should improve speed a fair amount.

**Comment by Skunk-Awol** [comment]
updated op with some handy dandy checkmarks!

**Comment by Enzoman34** [comment]
Mark, don't be a fuckboy

**Comment by dlom** [comment]
who me? :question:

**Comment by terabyte128** [comment]
The apple-touch-icon markup does not load anything unless it's relevant to the device.

**Comment by dlom** [comment]
https://mathiasbynens.be/notes/touch-icons#no-html

**Comment by terabyte128** [comment]
Won't work, static files can't go in the root.

**Comment by terabyte128** [comment]
Removed all CSS/JS from pages that specific files don't need to be on. 

**Note:** The index page does not do compression because it is loaded over SSL. Same goes for any pages that involve password POSTing. All other pages are unencrypted.

**Comment by terabyte128** [comment]
yeah i'm considering this closed. I've done all that I reasonably can. You can rewrite jquery if you want.

**Comment by dlom** [comment]
http://zeptojs.com/
