### ISSUE TITLE
Teleoperated: make more than last action undo-able

### ISSUE THREAD

**Issue by terabyte128** [FIRST-4030/frc-scout-2015#9]
Essentially, things can be stored as an array instead of as just a string.

**Comment by terabyte128** [comment]
DOne!

**Comment by terabyte128** [comment]
(may be buggy)

**Comment by Skunk-Awol** [comment]
Look forward to seeing this actually on production (last commit 3 days ago...)

**Comment by terabyte128** [comment]
sssshh
