### ISSUE TITLE
Selecting start height unselects auto selected totes added.

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#90]
When you stack something the totes added is preset to however many totes you have. When you select a start height that gets unselected. (Maybe visually or maybe not. I have no idea).

**Comment by terabyte128** [comment]
Oh right. That was in response to the bug that I fixed the other day. I'll fix it.

**Comment by Enzoman34** [comment]
Also start height carries over from last entry. Like if the last entry had astart height of 3 the totes added will be filtered accordingly. Works between matches and robots.

**Comment by terabyte128** [comment]
All these bugs should be fixed. (Have your minions do some testing though).
