### ISSUE TITLE
Attempt Push to Server Button (In Offline mode)

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#91]
In the prematch page (so they can click it in between rounds), I would love to see a button which would try to push things online. Currently the system which saves offline and then uploads it later is really unclear and a lot of teams are probably going to use the offline feature and then push with a single hotspot between matches. This would make that action faster.

**Comment by terabyte128** [comment]
There's a push button on the home page. Should there be one on prematch too?

**Comment by Enzoman34** [comment]
Yes please. Then they could do it without ever having to leave the page.

**Comment by terabyte128** [comment]
Added
