### ISSUE TITLE
Autonomous Container bug 

### ISSUE THREAD

**Issue by JayKingsFrc** [FIRST-4030/frc-scout-2015#96]
You have to do "acquired from the ground" before you can do "moved to auto zone."
I think bulldozing the container into Auto zone doesn't necessarily mean "acquired"

**Comment by terabyte128** [comment]
@Enzoman34 thoughts? This limitation was added by your request.

**Comment by Enzoman34** [comment]
Because you can get points from the center platform containers too, we need to know where the containers came from. We could redo it like the collected totes where its one button and then it brings up a second page with Container Source. this might be a better idea.

**Comment by JayKingsFrc** [comment]
I would agree to the intention. Nevertheless, the way it is will cause some confusion for many other teams' users. A simpler solution than creating another page would be disabling the moved totes button until other buttons are clicked at least once, but I don't mind adding another page idea as there won't be much going on in autonomous.

**Comment by terabyte128** [comment]
freaking finally done --- ended up adding another page, see 5af668f
