### ISSUE TITLE
Handy dandy auto select of "totes added to the stack" gets deselected once you do "Totes Stacked On Top Of"

### ISSUE THREAD

**Issue by JayKingsFrc** [FIRST-4030/frc-scout-2015#97]
Before doing "Totes Stacked On Top Of" button
![image](https://cloud.githubusercontent.com/assets/6064504/6386652/3dc0dfc0-bd31-11e4-8ce6-d75cd1944536.png)

number of totes in possession gets automatically selected which is nice! 

After clicking "Totes Stacked On Top Of"
![image](https://cloud.githubusercontent.com/assets/6064504/6386659/64f31428-bd31-11e4-87ff-638bb52af444.png)

But once you do the "Totes Stacked On Top Of," the auto-selected # of totes get deselected!

**Comment by terabyte128** [comment]
This has been fixed on the latest release and will be pushed later tonight.

**Comment by JayKingsFrc** [comment]
Awesome!!
