### ISSUE TITLE
in the pre-match, can you add a functionality which allow a scout to view the photo of robot once s/he type the team number?

### ISSUE THREAD

**Issue by JayKingsFrc** [FIRST-4030/frc-scout-2015#98]
This will help my scouts to identify which robot on the field they are supposed to track of.

**Comment by terabyte128** [comment]
There's not really any space to do this -- how might you suggest adding it?

**Comment by JayKingsFrc** [comment]
Right...well I know that Android has preview/instant message dialogue functionality such as Toast, but I guess there may not be a handy solution for the web-based app. I will just have my scouts check the bot profile if they don't recognize by the team #

**Comment by terabyte128** [comment]
That sounds like a better idea, would also avoid using data to pull down photos when teams don't necessarily need them. Recall that the scouting page is not intended to use any data once it's initially loaded.
